### ISSUE TITLE
Rename methods as well as your tests

### ISSUE THREAD

**Issue by grassiricardo** [grassiricardo/validation_contract#6]
Change the methods below to the following suggestions:

**is_required** for **required**
**is_fixed_len** for **fixed_len**
**is_email** for **email_valid**
**is_greater_than** for **greater_than**
**is_lower_than** for **lower_than**

**Remember to oversee the tests too.**

**Comment by ghost** [comment]
I'll tackle this

**Comment by ghost** [comment]
Just to confirm, the methods are already is_xxx. Do you want to remove the "is"?

**Comment by grassiricardo** [comment]
@Ksbugbee Yes, you want to remove the "is".

**Comment by ananya7** [comment]
@grassiricardo Please review my PR.
